version: '3.8'

services:
  staycation-web:
    build: .
    container_name: staycation-webserver
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=your_external_database_url_here
    volumes:
      - .:/app
    restart: always
    networks:
      - my-main-net

networks:
  my-main-net:
    external: true