"""Add additional fields to Booking model

Revision ID: 3cb0e5466048
Revises: 672d0c9daf3b
Create Date: 2024-07-03 03:27:19.399057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb0e5466048'
down_revision = '672d0c9daf3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('country_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'cities', ['city_id'], ['id'])
        batch_op.create_foreign_key(None, 'states', ['state_id'], ['id'])
        batch_op.create_foreign_key(None, 'countries', ['country_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('city_id')
        batch_op.drop_column('state_id')
        batch_op.drop_column('country_id')
        batch_op.drop_column('address')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
