"""Add state_id to hotel model

Revision ID: 672d0c9daf3b
Revises: 80669efc47d5
Create Date: 2024-06-29 10:20:52.865031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672d0c9daf3b'
down_revision = '80669efc47d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'states', ['state_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('state_id')

    # ### end Alembic commands ###
