"""remove code from states table

Revision ID: 80669efc47d5
Revises: 4d67a935c9ea
Create Date: 2024-06-29 06:44:01.527524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80669efc47d5'
down_revision = '4d67a935c9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', mysql.VARCHAR(length=8), nullable=False))

    # ### end Alembic commands ###
