"""Add unique booking_id to Booking model

Revision ID: ce5bed33550e
Revises: f5b886996c44
Create Date: 2024-07-04 03:30:30.325685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5bed33550e'
down_revision = 'f5b886996c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['booking_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###
