"""Update Booking model to fix no_of_rooms column

Revision ID: f5b886996c44
Revises: 3cb0e5466048
Create Date: 2024-07-03 03:38:45.754971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5b886996c44'
down_revision = '3cb0e5466048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_of_rooms', sa.Integer(), nullable=False))
        batch_op.drop_column('special_requirements')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_requirements', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('no_of_rooms')

    # ### end Alembic commands ###
